In [1]:

import cornac
from cornac.data import TextModality, ImageModality
from cornac.datasets import amazon_clothing
from cornac.eval_methods import RatioSplit

FM model is only supported on Linux.
Windows executable can be found at http://www.libfm.org.


In [2]:
feedback = amazon_clothing.load_feedback()
image_features, image_item_ids = amazon_clothing.load_visual_feature()  # BIG file
docs, text_item_ids = amazon_clothing.load_text()

Data from https://static.preferred.ai/cornac/datasets/amazon_clothing/rating.zip
will be cached into C:\Users\damie\.cornac\amazon_clothing/rating.txt


0.00B [00:00, ?B/s]

Unzipping ...
File cached!
Data from https://static.preferred.ai/cornac/datasets/amazon_clothing/image.zip
will be cached into C:\Users\damie\.cornac\amazon_clothing/image_features.npy


0.00B [00:00, ?B/s]

Unzipping ...
File cached!
Data from https://static.preferred.ai/cornac/datasets/amazon_clothing/item_ids.zip
will be cached into C:\Users\damie\.cornac\amazon_clothing/item_ids.txt


0.00B [00:00, ?B/s]

Unzipping ...
File cached!
Data from https://static.preferred.ai/cornac/datasets/amazon_clothing/text.zip
will be cached into C:\Users\damie\.cornac\amazon_clothing/text.txt


0.00B [00:00, ?B/s]

Unzipping ...
File cached!


In [8]:
print(len(image_features))
print(image_features)

print(len(image_item_ids))

3393
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 1.10210001 0.         2.33089995]
 [1.1006     0.         1.73380005 ... 0.         0.         0.74169999]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         7.42589998 ... 1.7529     0.         0.9716    ]
 [0.         0.         1.57350004 ... 0.         0.         0.        ]]
3393


In [9]:
image_features[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [20]:
import numpy as np
import pandas as pd
data = np.load(r"C:\Users\damie\.cornac\amazon_clothing\image_features.npy")

print(len(data))
print(len(data[0]))
print(type(data))
print(type(data[0]))

3393
4096
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [23]:
df_test = pd.DataFrame(data[0])

df_test.describe()

0
count  4096.000000
mean      0.386342
std       1.237126
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max      11.001200

In [34]:
import tensorflow as tf
from tensorflow.keras.applications import VGG16
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input
import numpy as np

# Load pre-trained VGG16 model
model = VGG16(weights='imagenet', include_top=False)

# Load and preprocess image
img_path = '../data/05_model_input/images/1.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

# Extract features
print("Executing prediction")
features = model.predict(x)
print(features.shape)

Executing prediction
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 656ms/step
(1, 7, 7, 512)


In [33]:
print(features.shape)

features_flat = features.flatten()

print(features_flat.shape)


(1, 7, 7, 512)
(25088,)
